### ISSUE TITLE
How this works ?

### ISSUE THREAD

**Issue by profesionalleet1337** [Bhai4You/vehicleosint#1]
How this  could be test if it work's ? Does it install on Kali/Termux, or its some kind of telegram bot ? I can't understand the principe of this tool, I want to test it , but please expalin how to set up it/ installed it ! {Does it will show information about EUROPE car's like in GREECE,MACEDONIA for example )?

**Comment by Bhai4You** [comment]
this is application that show Indian vehicle owners details so unfortunately you can't test it because it was not made for Europe!!

Let me know if you have any other queries
Thanks.

**Comment by profesionalleet1337** [comment]
> this is application that show Indian vehicle owners details so unfortunately you can't test it because it was not made for Europe!!
> 
> Let me know if you have any other queries Thanks.

Thank's for your reply ! So .. Can be improved to search/show for European country - especially for one country , or this can't be done ? I'm lookin for way to check about my "state" , but there is nothing that work.. Maybe u could advise me ?
